# Generated by Django 6.0.1 on 2026-04-26 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rbt_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('subject_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('PROJECT', 'Project')], max_length=20)),
                ('credits', models.IntegerField()),
                ('hours', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='COPOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po', models.IntegerField()),
                ('value', models.IntegerField()),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_app.co')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('hours', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_app.subject')),
            ],
        ),
        migrations.AddField(
            model_name='co',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_app.subject'),
        ),
    ]
