# Generated by Django 6.0.1 on 2026-04-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='content',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='hands_on',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='self_learning',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FACULTY', 'Faculty Approved'), ('BOS', 'BOS Approved'), ('HOD', 'HOD Approved')], default='DRAFT'),
        ),
        migrations.AlterField(
            model_name='copomapping',
            name='value',
            field=models.IntegerField(choices=[(1, 'L'), (2, 'M'), (3, 'H')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(max_length=20),
        ),
    ]
