# Generated by Django 6.0.1 on 2026-04-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_app', '0002_module_content_module_hands_on_module_self_learning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='content',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='module',
            name='hands_on',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='module',
            name='self_learning',
            field=models.TextField(default='NA'),
        ),
    ]
