# Generated by Django 6.0.1 on 2026-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_app', '0003_alter_module_content_alter_module_hands_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co',
            name='rbt_level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_type',
        ),
        migrations.AlterField(
            model_name='copomapping',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
    ]
